# Generated by Django 2.2 on 2020-02-26 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot_bag', '0002_databases_questionnaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='username',
            new_name='Ug_id',
        ),
    ]
