# Generated by Django 2.2.4 on 2020-03-24 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot_bag', '0003_auto_20200226_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Result', models.TextField(verbose_name='诊断结果')),
                ('ID_Card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot_bag.Questionnaire')),
            ],
        ),
    ]
