# Generated by Django 2.2.4 on 2020-03-24 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot_bag', '0004_medicalform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalform',
            old_name='Result',
            new_name='Med_Result',
        ),
    ]
